# Generated by Django 4.2.27 on 2025-12-06 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='部门名称')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='部门代码')),
                ('level', models.IntegerField(db_index=True, default=1, verbose_name='部门层级')),
                ('path', models.CharField(blank=True, help_text='如：1/2/3', max_length=500, null=True, verbose_name='部门路径')),
                ('description', models.TextField(blank=True, null=True, verbose_name='部门描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否激活')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='部门负责人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='apps_users.department', verbose_name='父部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'sys_department',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, max_length=500, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='头像')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='地址')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='职位')),
                ('employee_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='工号')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='apps_users.department', verbose_name='部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
                'db_table': 'sys_user_profile',
            },
        ),
    ]
