# Generated by Django 4.2.27 on 2025-12-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='用户 ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='用户名')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('view', '查看'), ('login', '登录'), ('logout', '登出'), ('export', '导出'), ('import', '导入'), ('other', '其他')], db_index=True, max_length=50, verbose_name='操作类型')),
                ('resource_type', models.CharField(db_index=True, max_length=100, verbose_name='资源类型')),
                ('resource_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='资源 ID')),
                ('resource_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='资源名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='操作描述')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='HTTP 方法')),
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='请求路径')),
                ('request_params', models.TextField(blank=True, null=True, verbose_name='请求参数')),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='IP 地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='用户代理')),
                ('status', models.SmallIntegerField(choices=[(1, '成功'), (0, '失败')], db_index=True, default=1, verbose_name='操作状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('execution_time', models.IntegerField(blank=True, null=True, verbose_name='执行时间（毫秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'sys_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='sys_audit_l_user_id_cce000_idx'), models.Index(fields=['action', 'resource_type'], name='sys_audit_l_action_c8b8d0_idx'), models.Index(fields=['status', 'created_at'], name='sys_audit_l_status_05bd3b_idx')],
            },
        ),
    ]
